-- =====================================================================
-- T-SQL Load Script for retailanalytics – final version (with deliverydays fix)
-- Loads all CSV files generated by the Python script
-- Includes stage PRINT messages for progress monitoring
-- FIX: Forces deliverydays = 0 for In-Store transactions during load
-- =====================================================================

USE master;
GO

PRINT '============================================================';
PRINT 'STEP 0: Prepare database';
PRINT '============================================================';

IF DB_ID('retailanalytics') IS NOT NULL
BEGIN
    PRINT '  -> Dropping existing database retailanalytics...';
    ALTER DATABASE retailanalytics SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE retailanalytics;
END
GO

PRINT '  -> Creating fresh database retailanalytics...';
CREATE DATABASE retailanalytics;
GO
ALTER DATABASE retailanalytics SET RECOVERY SIMPLE;
GO
USE retailanalytics;
GO

PRINT '============================================================';
PRINT 'STEP 1: Drop existing objects (views, tables)';
PRINT '============================================================';

IF OBJECT_ID('dbo.vw_sales', 'V') IS NOT NULL DROP VIEW dbo.vw_sales;
IF OBJECT_ID('dbo.vw_customers', 'V') IS NOT NULL DROP VIEW dbo.vw_customers;
IF OBJECT_ID('dbo.vw_dates', 'V') IS NOT NULL DROP VIEW dbo.vw_dates;
IF OBJECT_ID('dbo.vw_products', 'V') IS NOT NULL DROP VIEW dbo.vw_products;
IF OBJECT_ID('dbo.vw_promotions', 'V') IS NOT NULL DROP VIEW dbo.vw_promotions;
IF OBJECT_ID('dbo.vw_stores', 'V') IS NOT NULL DROP VIEW dbo.vw_stores;
GO

IF OBJECT_ID('dbo.factsales', 'U') IS NOT NULL DROP TABLE dbo.factsales;
IF OBJECT_ID('dbo.dimdate', 'U') IS NOT NULL DROP TABLE dbo.dimdate;
IF OBJECT_ID('dbo.dimcustomer', 'U') IS NOT NULL DROP TABLE dbo.dimcustomer;
IF OBJECT_ID('dbo.dimproduct', 'U') IS NOT NULL DROP TABLE dbo.dimproduct;
IF OBJECT_ID('dbo.dimstore', 'U') IS NOT NULL DROP TABLE dbo.dimstore;
IF OBJECT_ID('dbo.dimpromotion', 'U') IS NOT NULL DROP TABLE dbo.dimpromotion;
GO

PRINT '  -> Old objects dropped.';
GO

PRINT '============================================================';
PRINT 'STEP 2: Create dimension and fact tables';
PRINT '============================================================';

CREATE TABLE dbo.dimdate (
    datekey INT NOT NULL,
    fulldate DATE NOT NULL,
    year SMALLINT NOT NULL,
    quarternumber TINYINT NOT NULL,
    quartername NCHAR(2) NOT NULL,
    monthnumber TINYINT NOT NULL,
    monthname NVARCHAR(20) NOT NULL,
    weekdaynumber TINYINT NOT NULL,
    weekdayname NVARCHAR(20) NOT NULL,
    isweekend BIT NOT NULL,
    yearmonth NCHAR(7) NOT NULL,
    yearmonthnumber INT NOT NULL,
    yearquarter NVARCHAR(7) NOT NULL,
    yearquarternumber INT NOT NULL,
    yearweek NVARCHAR(8) NOT NULL,
    yearweeknumber INT NOT NULL,
    isholiday BIT NOT NULL
);
GO

CREATE TABLE dbo.dimcustomer (
    customerid INT NOT NULL,
    fullname NVARCHAR(100) NOT NULL,
    email NVARCHAR(100) NOT NULL,
    age TINYINT NOT NULL,
    gender NVARCHAR(20) NOT NULL,
    city NVARCHAR(50) NOT NULL,
    tier NVARCHAR(20) NOT NULL,
    points INT NOT NULL,
    isactive BIT NOT NULL,
    lang NVARCHAR(10) NOT NULL,
    totalspend DECIMAL(18,2) NOT NULL,
    regdate DATE NOT NULL,
    annualincome DECIMAL(18,2) NOT NULL,
    incomebracket NVARCHAR(20) NOT NULL,
    education NVARCHAR(50) NOT NULL,
    maritalstatus NVARCHAR(20) NOT NULL,
    childrencount TINYINT NOT NULL,
    loyaltysegment NVARCHAR(20) NOT NULL,
    satisfactionscore DECIMAL(5,1) NOT NULL,
    dayssincelastpurchase INT NOT NULL,
    hassubscription BIT NOT NULL,
    preferredcontact NVARCHAR(20) NOT NULL,
    spendmultiplier DECIMAL(10,3) NOT NULL
);
GO

CREATE TABLE dbo.dimproduct (
    productid INT NOT NULL,
    name NVARCHAR(150) NOT NULL,
    category NVARCHAR(50) NOT NULL,
    brand NVARCHAR(50) NOT NULL,
    unitcost DECIMAL(18,2) NOT NULL,
    unitprice DECIMAL(18,2) NOT NULL,
    margin_pct DECIMAL(5,4) NOT NULL,
    weight DECIMAL(10,2) NOT NULL,
    color NVARCHAR(20) NOT NULL,
    material NVARCHAR(50) NOT NULL,
    supplierid INT NOT NULL,
    isactive BIT NOT NULL,
    minstock INT NOT NULL,
    tax_rate DECIMAL(5,4) NOT NULL,
    haswarranty BIT NOT NULL,
    ecofriendly BIT NOT NULL,
    seasonalityfactor DECIMAL(5,2) NOT NULL,
    warrantymonths TINYINT NOT NULL,
    ecoscore TINYINT NOT NULL,
    releaseyear SMALLINT NOT NULL,
    skucount INT NOT NULL,
    isdiscontinued BIT NOT NULL,
    productrating DECIMAL(3,1) NOT NULL,
    stockstatus NVARCHAR(20) NOT NULL
);
GO

CREATE TABLE dbo.dimstore (
    storeid INT NOT NULL,
    storename NVARCHAR(150) NOT NULL,
    city NVARCHAR(50) NOT NULL,
    type NVARCHAR(50) NOT NULL,
    staff SMALLINT NOT NULL,
    sizem2 INT NOT NULL,
    hascafe BIT NOT NULL,
    openingyear SMALLINT NOT NULL,
    region NVARCHAR(50) NOT NULL,
    renovationyear SMALLINT NOT NULL,
    parkingspots SMALLINT NOT NULL,
    storerating DECIMAL(3,1) NOT NULL,
    hasdeliveryservice BIT NOT NULL,
    floornumber TINYINT NOT NULL,
    distancetocitycenterkm DECIMAL(8,1) NOT NULL,
    annualrentcost DECIMAL(18,2) NOT NULL,
    storesizemultiplier DECIMAL(10,3) NOT NULL
);
GO

CREATE TABLE dbo.dimpromotion (
    promoid INT NOT NULL,
    promoname NVARCHAR(150) NOT NULL,
    discount_pct DECIMAL(5,3) NOT NULL,
    discount_fixed DECIMAL(10,2) NOT NULL,
    type NVARCHAR(50) NOT NULL,
    isactive BIT NOT NULL,
    minspend INT NOT NULL,
    channel NVARCHAR(50) NOT NULL,
    budget DECIMAL(18,2) NOT NULL,
    startdate DATE NOT NULL,
    enddate DATE NOT NULL,
    targetaudience NVARCHAR(50) NOT NULL,
    maxdiscountcap DECIMAL(18,2) NOT NULL,
    isstackable BIT NOT NULL,
    redemption_rate DECIMAL(5,3) NOT NULL,
    coderequired BIT NOT NULL,
    promoupliftfactor DECIMAL(6,3) NOT NULL
);
GO

CREATE TABLE dbo.factsales (
    salesid BIGINT NOT NULL,
    datekey INT NOT NULL,
    productid INT NOT NULL,
    customerid INT NOT NULL,
    storeid INT NOT NULL,
    promoid INT NULL,
    qty TINYINT NOT NULL,
    unitprice DECIMAL(18,2) NOT NULL,
    tax_rate DECIMAL(5,4) NOT NULL,
    net DECIMAL(18,2) NOT NULL,
    payment NVARCHAR(20) NOT NULL,
    channel NVARCHAR(20) NOT NULL,
    grossvalue DECIMAL(18,2) NOT NULL,
    discountamount DECIMAL(18,2) NOT NULL,
    taxamount DECIMAL(18,2) NOT NULL,
    shipcost DECIMAL(18,2) NOT NULL,
    isreturn BIT NOT NULL,
    shipweight DECIMAL(10,2) NOT NULL,
    discountapplied BIT NOT NULL,
    returnreason NVARCHAR(50) NULL,
    deliverydays TINYINT NOT NULL
);
GO

PRINT '  -> Tables created successfully.';
GO

PRINT '============================================================';
PRINT 'STEP 3: Load dim_date from CSV';
PRINT '============================================================';

DROP TABLE IF EXISTS #dimdate_staging;
CREATE TABLE #dimdate_staging (
    datekey NVARCHAR(50), fulldate NVARCHAR(50), year NVARCHAR(50),
    quarternumber NVARCHAR(50), quartername NVARCHAR(50), monthnumber NVARCHAR(50),
    monthname NVARCHAR(50), weekdaynumber NVARCHAR(50), weekdayname NVARCHAR(50),
    isweekend NVARCHAR(50), yearmonth NVARCHAR(50), yearmonthnumber NVARCHAR(50),
    yearquarter NVARCHAR(50), yearquarternumber NVARCHAR(50), yearweek NVARCHAR(50),
    yearweeknumber NVARCHAR(50), isholiday NVARCHAR(50)
);
BULK INSERT #dimdate_staging FROM 'c:\data\dim_date.csv' 
WITH (FIRSTROW=2, FIELDTERMINATOR=',', ROWTERMINATOR='0x0A', TABLOCK, CODEPAGE='65001');

INSERT INTO dbo.dimdate SELECT
    TRY_CAST(datekey AS INT), TRY_CAST(fulldate AS DATE), TRY_CAST(year AS SMALLINT),
    TRY_CAST(quarternumber AS TINYINT), quartername, TRY_CAST(monthnumber AS TINYINT),
    monthname, TRY_CAST(weekdaynumber AS TINYINT), weekdayname,
    CASE WHEN isweekend IN ('1','True','true','TRUE') THEN 1 ELSE 0 END,
    yearmonth, TRY_CAST(yearmonthnumber AS INT), yearquarter,
    TRY_CAST(yearquarternumber AS INT), yearweek, TRY_CAST(yearweeknumber AS INT),
    CASE WHEN isholiday IN ('1','True','true','TRUE') THEN 1 ELSE 0 END
FROM #dimdate_staging;
DROP TABLE #dimdate_staging;
PRINT '  -> dim_date loaded.';
GO

PRINT '============================================================';
PRINT 'STEP 4: Load dim_customer from CSV';
PRINT '============================================================';

DROP TABLE IF EXISTS #stg_customer;
CREATE TABLE #stg_customer (
    customerid NVARCHAR(50), fullname NVARCHAR(100), email NVARCHAR(100),
    age NVARCHAR(50), gender NVARCHAR(50), city NVARCHAR(50), tier NVARCHAR(50),
    points NVARCHAR(50), isactive NVARCHAR(50), lang NVARCHAR(50),
    totalspend NVARCHAR(50), regdate NVARCHAR(50), annualincome NVARCHAR(50),
    incomebracket NVARCHAR(50), education NVARCHAR(50), maritalstatus NVARCHAR(50),
    childrencount NVARCHAR(50), loyaltysegment NVARCHAR(50), satisfactionscore NVARCHAR(50),
    dayssincelastpurchase NVARCHAR(50), hassubscription NVARCHAR(50),
    preferredcontact NVARCHAR(50), spendmultiplier NVARCHAR(50)
);
BULK INSERT #stg_customer FROM 'c:\data\dim_customer.csv' 
WITH (FIRSTROW=2, FIELDTERMINATOR=',', ROWTERMINATOR='0x0A', TABLOCK, CODEPAGE='65001');

INSERT INTO dbo.dimcustomer SELECT
    TRY_CAST(customerid AS INT), fullname, email, TRY_CAST(age AS TINYINT), gender, city, tier,
    TRY_CAST(points AS INT), TRY_CAST(isactive AS BIT), lang,
    TRY_CAST(totalspend AS DECIMAL(18,2)), TRY_CAST(regdate AS DATE),
    TRY_CAST(annualincome AS DECIMAL(18,2)), incomebracket, education, maritalstatus,
    TRY_CAST(childrencount AS TINYINT), loyaltysegment, TRY_CAST(satisfactionscore AS DECIMAL(5,1)),
    TRY_CAST(dayssincelastpurchase AS INT), TRY_CAST(hassubscription AS BIT), preferredcontact,
    ISNULL(TRY_CAST(spendmultiplier AS DECIMAL(10,3)), 1.0)
FROM #stg_customer;
DROP TABLE #stg_customer;
PRINT '  -> dim_customer loaded.';
GO

PRINT '============================================================';
PRINT 'STEP 5: Load dim_product from CSV';
PRINT '============================================================';

DROP TABLE IF EXISTS #stg_product;
CREATE TABLE #stg_product (
    productid NVARCHAR(50), name NVARCHAR(150), category NVARCHAR(50),
    brand NVARCHAR(50), unitcost NVARCHAR(50), unitprice NVARCHAR(50),
    margin_pct NVARCHAR(50), weight NVARCHAR(50), color NVARCHAR(20),
    material NVARCHAR(50), supplierid NVARCHAR(50), isactive NVARCHAR(50),
    minstock NVARCHAR(50), tax_rate NVARCHAR(50), haswarranty NVARCHAR(50),
    ecofriendly NVARCHAR(50), seasonalityfactor NVARCHAR(50), warrantymonths NVARCHAR(50),
    ecoscore NVARCHAR(50), releaseyear NVARCHAR(50), skucount NVARCHAR(50),
    isdiscontinued NVARCHAR(50), productrating NVARCHAR(50), stockstatus NVARCHAR(50)
);
BULK INSERT #stg_product FROM 'c:\data\dim_product.csv' 
WITH (FIRSTROW=2, FIELDTERMINATOR=',', ROWTERMINATOR='0x0A', TABLOCK, CODEPAGE='65001');

INSERT INTO dbo.dimproduct SELECT
    TRY_CAST(productid AS INT), name, category, brand,
    TRY_CAST(unitcost AS DECIMAL(18,2)), TRY_CAST(unitprice AS DECIMAL(18,2)),
    TRY_CAST(margin_pct AS DECIMAL(5,4)), TRY_CAST(weight AS DECIMAL(10,2)), color,
    material, TRY_CAST(supplierid AS INT), TRY_CAST(isactive AS BIT),
    TRY_CAST(minstock AS INT), TRY_CAST(tax_rate AS DECIMAL(5,4)), TRY_CAST(haswarranty AS BIT),
    TRY_CAST(ecofriendly AS BIT), TRY_CAST(seasonalityfactor AS DECIMAL(5,2)),
    TRY_CAST(warrantymonths AS TINYINT), TRY_CAST(ecoscore AS TINYINT),
    TRY_CAST(releaseyear AS SMALLINT), TRY_CAST(skucount AS INT),
    TRY_CAST(isdiscontinued AS BIT), TRY_CAST(productrating AS DECIMAL(3,1)),
    stockstatus
FROM #stg_product;
DROP TABLE #stg_product;
PRINT '  -> dim_product loaded.';
GO

PRINT '============================================================';
PRINT 'STEP 6: Load dim_store from CSV';
PRINT '============================================================';

DROP TABLE IF EXISTS #stg_store;
CREATE TABLE #stg_store (
    storeid NVARCHAR(50), storename NVARCHAR(150), city NVARCHAR(50),
    type NVARCHAR(50), staff NVARCHAR(50), sizem2 NVARCHAR(50),
    hascafe NVARCHAR(50), openingyear NVARCHAR(50), region NVARCHAR(50),
    renovationyear NVARCHAR(50), parkingspots NVARCHAR(50), storerating NVARCHAR(50),
    hasdeliveryservice NVARCHAR(50), floornumber NVARCHAR(50),
    distancetocitycenterkm NVARCHAR(50), annualrentcost NVARCHAR(50),
    storesizemultiplier NVARCHAR(50)
);
BULK INSERT #stg_store FROM 'c:\data\dim_store.csv' 
WITH (FIRSTROW=2, FIELDTERMINATOR=',', ROWTERMINATOR='0x0A', TABLOCK, CODEPAGE='65001');

INSERT INTO dbo.dimstore SELECT
    TRY_CAST(storeid AS INT), storename, city, type, TRY_CAST(staff AS SMALLINT),
    TRY_CAST(sizem2 AS INT), TRY_CAST(hascafe AS BIT), TRY_CAST(openingyear AS SMALLINT),
    region, TRY_CAST(renovationyear AS SMALLINT), TRY_CAST(parkingspots AS SMALLINT),
    TRY_CAST(storerating AS DECIMAL(3,1)), TRY_CAST(hasdeliveryservice AS BIT),
    TRY_CAST(floornumber AS TINYINT), TRY_CAST(distancetocitycenterkm AS DECIMAL(8,1)),
    TRY_CAST(annualrentcost AS DECIMAL(18,2)), ISNULL(TRY_CAST(storesizemultiplier AS DECIMAL(10,3)), 1.0)
FROM #stg_store;
DROP TABLE #stg_store;
PRINT '  -> dim_store loaded.';
GO

PRINT '============================================================';
PRINT 'STEP 7: Load dim_promotion from CSV';
PRINT '============================================================';

DROP TABLE IF EXISTS #stg_promo;
CREATE TABLE #stg_promo (
    promoid NVARCHAR(50), promoname NVARCHAR(150), discount_pct NVARCHAR(50),
    discount_fixed NVARCHAR(50), type NVARCHAR(50), isactive NVARCHAR(50),
    minspend NVARCHAR(50), channel NVARCHAR(50), budget NVARCHAR(50),
    startdate NVARCHAR(50), enddate NVARCHAR(50), targetaudience NVARCHAR(50),
    maxdiscountcap NVARCHAR(50), isstackable NVARCHAR(50), redemption_rate NVARCHAR(50),
    coderequired NVARCHAR(50), promoupliftfactor NVARCHAR(50)
);
BULK INSERT #stg_promo FROM 'c:\data\dim_promotion.csv' 
WITH (FIRSTROW=2, FIELDTERMINATOR=',', ROWTERMINATOR='0x0A', TABLOCK, CODEPAGE='65001');

INSERT INTO dbo.dimpromotion SELECT
    TRY_CAST(promoid AS INT), promoname, TRY_CAST(discount_pct AS DECIMAL(5,3)),
    TRY_CAST(discount_fixed AS DECIMAL(10,2)), type, TRY_CAST(isactive AS BIT),
    TRY_CAST(minspend AS INT), channel, TRY_CAST(budget AS DECIMAL(18,2)),
    TRY_CAST(startdate AS DATE), TRY_CAST(enddate AS DATE), targetaudience,
    TRY_CAST(maxdiscountcap AS DECIMAL(18,2)), TRY_CAST(isstackable AS BIT),
    TRY_CAST(redemption_rate AS DECIMAL(5,3)), TRY_CAST(coderequired AS BIT),
    ISNULL(TRY_CAST(promoupliftfactor AS DECIMAL(6,3)), 1.0)
FROM #stg_promo;
DROP TABLE #stg_promo;
PRINT '  -> dim_promotion loaded.';
GO

PRINT '============================================================';
PRINT 'STEP 8: Load fact_sales from CSV (this may take a while)';
PRINT '============================================================';

DROP TABLE IF EXISTS #stg_fact;
CREATE TABLE #stg_fact (
    salesid NVARCHAR(50), datekey NVARCHAR(50), productid NVARCHAR(50),
    customerid NVARCHAR(50), storeid NVARCHAR(50), promoid NVARCHAR(50),
    qty NVARCHAR(50), unitprice NVARCHAR(50), tax_rate NVARCHAR(50),
    net NVARCHAR(50), payment NVARCHAR(50), channel NVARCHAR(50),
    grossvalue NVARCHAR(50), discountamount NVARCHAR(50), taxamount NVARCHAR(50),
    shipcost NVARCHAR(50), isreturn NVARCHAR(50), shipweight NVARCHAR(50),
    discountapplied NVARCHAR(50), returnreason NVARCHAR(50), deliverydays NVARCHAR(50)
);
BULK INSERT #stg_fact FROM 'c:\data\fact_sales.csv' 
WITH (FIRSTROW=2, FIELDTERMINATOR=',', ROWTERMINATOR='0x0A', TABLOCK, CODEPAGE='65001', KEEPNULLS);

INSERT INTO dbo.factsales SELECT
    TRY_CAST(salesid AS BIGINT),
    TRY_CAST(datekey AS INT),
    TRY_CAST(productid AS INT),
    TRY_CAST(customerid AS INT),
    TRY_CAST(storeid AS INT),
    NULLIF(TRY_CAST(promoid AS INT), 0),
    TRY_CAST(qty AS TINYINT),
    TRY_CAST(unitprice AS DECIMAL(18,2)),
    TRY_CAST(tax_rate AS DECIMAL(5,4)),
    TRY_CAST(net AS DECIMAL(18,2)),
    payment,
    channel,
    TRY_CAST(grossvalue AS DECIMAL(18,2)),
    TRY_CAST(discountamount AS DECIMAL(18,2)),
    TRY_CAST(taxamount AS DECIMAL(18,2)),
    TRY_CAST(shipcost AS DECIMAL(18,2)),
    TRY_CAST(isreturn AS BIT),
    TRY_CAST(shipweight AS DECIMAL(10,2)),
    TRY_CAST(discountapplied AS BIT),
    NULLIF(returnreason, ''),
    -- FIX: Force deliverydays = 0 for In-Store transactions
    CASE WHEN channel = 'In-Store' THEN 0 ELSE ISNULL(TRY_CAST(NULLIF(deliverydays, '') AS TINYINT), 1) END AS deliverydays
FROM #stg_fact;
DROP TABLE #stg_fact;
PRINT '  -> fact_sales loaded.';
GO

PRINT '============================================================';
PRINT 'STEP 9: Fix any invalid promoid values (set to NULL)';
PRINT '============================================================';

UPDATE dbo.factsales
SET promoid = NULL
WHERE promoid IS NOT NULL 
  AND NOT EXISTS (SELECT 1 FROM dbo.dimpromotion WHERE promoid = dbo.factsales.promoid);
PRINT '  -> Invalid promoids fixed.';
GO

PRINT '============================================================';
PRINT 'STEP 10: Add primary keys and foreign keys';
PRINT '============================================================';

ALTER TABLE dbo.dimdate ADD CONSTRAINT pk_dimdate PRIMARY KEY (datekey);
ALTER TABLE dbo.dimcustomer ADD CONSTRAINT pk_dimcustomer PRIMARY KEY (customerid);
ALTER TABLE dbo.dimproduct ADD CONSTRAINT pk_dimproduct PRIMARY KEY (productid);
ALTER TABLE dbo.dimstore ADD CONSTRAINT pk_dimstore PRIMARY KEY (storeid);
ALTER TABLE dbo.dimpromotion ADD CONSTRAINT pk_dimpromotion PRIMARY KEY (promoid);
GO

ALTER TABLE dbo.factsales ADD CONSTRAINT pk_factsales PRIMARY KEY NONCLUSTERED (salesid);
CREATE CLUSTERED COLUMNSTORE INDEX cci_factsales ON dbo.factsales;
GO

ALTER TABLE dbo.factsales ADD CONSTRAINT fk_fact_date FOREIGN KEY (datekey) REFERENCES dbo.dimdate(datekey);
ALTER TABLE dbo.factsales ADD CONSTRAINT fk_fact_customer FOREIGN KEY (customerid) REFERENCES dbo.dimcustomer(customerid);
ALTER TABLE dbo.factsales ADD CONSTRAINT fk_fact_product FOREIGN KEY (productid) REFERENCES dbo.dimproduct(productid);
ALTER TABLE dbo.factsales ADD CONSTRAINT fk_fact_store FOREIGN KEY (storeid) REFERENCES dbo.dimstore(storeid);
ALTER TABLE dbo.factsales ADD CONSTRAINT fk_fact_promo FOREIGN KEY (promoid) REFERENCES dbo.dimpromotion(promoid);
GO

PRINT '  -> Primary and foreign keys added.';
GO

PRINT '============================================================';
PRINT 'STEP 11: Create additional indexes';
PRINT '============================================================';

CREATE NONCLUSTERED INDEX ix_dimdate_year_month ON dbo.dimdate (year, monthnumber) INCLUDE (fulldate, isweekend, isholiday);
CREATE NONCLUSTERED INDEX ix_dimcustomer_tier_city ON dbo.dimcustomer (tier, city) INCLUDE (loyaltysegment, isactive, annualincome);
CREATE NONCLUSTERED INDEX ix_dimproduct_category_brand ON dbo.dimproduct (category, brand) INCLUDE (unitprice, tax_rate, isactive, stockstatus);
CREATE NONCLUSTERED INDEX ix_dimstore_region_type ON dbo.dimstore (region, type) INCLUDE (city, storerating, storesizemultiplier);
CREATE NONCLUSTERED INDEX ix_dimpromotion_type_channel ON dbo.dimpromotion (type, channel) INCLUDE (discount_pct, discount_fixed, isactive, promoupliftfactor);
GO

PRINT '  -> Additional indexes created.';
GO

PRINT '============================================================';
PRINT 'STEP 12: Update statistics';
PRINT '============================================================';

UPDATE STATISTICS dbo.dimdate WITH FULLSCAN;
UPDATE STATISTICS dbo.dimcustomer WITH FULLSCAN;
UPDATE STATISTICS dbo.dimproduct WITH FULLSCAN;
UPDATE STATISTICS dbo.dimstore WITH FULLSCAN;
UPDATE STATISTICS dbo.dimpromotion WITH FULLSCAN;
UPDATE STATISTICS dbo.factsales WITH FULLSCAN;
PRINT '  -> Statistics updated.';
GO

PRINT '============================================================';
PRINT 'STEP 13: Create views';
PRINT '============================================================';
GO

CREATE VIEW dbo.vw_dates AS SELECT * FROM dbo.dimdate;
GO
CREATE VIEW dbo.vw_customers AS SELECT * FROM dbo.dimcustomer;
GO
CREATE VIEW dbo.vw_products AS SELECT * FROM dbo.dimproduct;
GO
CREATE VIEW dbo.vw_stores AS SELECT * FROM dbo.dimstore;
GO
CREATE VIEW dbo.vw_promotions AS SELECT * FROM dbo.dimpromotion;
GO
CREATE VIEW dbo.vw_sales AS SELECT * FROM dbo.factsales;
GO

PRINT '  -> Views created.';
GO

PRINT '============================================================';
PRINT 'FINAL STEP: Row counts';
PRINT '============================================================';

SELECT 'dimdate' AS table_name, COUNT(*) FROM dbo.dimdate UNION ALL
SELECT 'dimcustomer', COUNT(*) FROM dbo.dimcustomer UNION ALL
SELECT 'dimproduct', COUNT(*) FROM dbo.dimproduct UNION ALL
SELECT 'dimstore', COUNT(*) FROM dbo.dimstore UNION ALL
SELECT 'dimpromotion', COUNT(*) FROM dbo.dimpromotion UNION ALL
SELECT 'factsales', COUNT(*) FROM dbo.factsales;
GO

PRINT '============================================================';
PRINT '✅ Database retailanalytics loaded successfully.';
PRINT '============================================================';