-- =====================================================================
-- MODEL VALIDATION (compatible with Python v46 – no dimmanager, no denormalized columns)
-- =====================================================================

WITH model_checks AS (
    -- 1. Star schema: factsales must have foreign keys to all 5 core dimensions
    SELECT
        'star_schema' AS check_category,
        'factsales has foreign keys to all 5 dimensions (date, product, customer, store, promotion)' AS check_description,
        CASE WHEN COUNT(*) = 5 THEN 'OK' ELSE 'ISSUE' END AS check_result,
        COUNT(*) AS details
    FROM sys.foreign_keys
    WHERE parent_object_id = OBJECT_ID('dbo.factsales')
      AND referenced_object_id IN (OBJECT_ID('dbo.dimdate'), OBJECT_ID('dbo.dimproduct'),
                                   OBJECT_ID('dbo.dimcustomer'), OBJECT_ID('dbo.dimstore'),
                                   OBJECT_ID('dbo.dimpromotion'))
    UNION ALL

    -- 2. Fact purity: factsales contains only allowed columns (no extra columns)
    --    The list includes all expected columns from Python v46 (no denormalized columns)
    SELECT
        'fact_purity',
        'factsales contains only keys, measures, and allowed descriptors (no extra columns)' AS check_description,
        CASE WHEN COUNT(*) = 0 THEN 'OK' ELSE 'ISSUE' END,
        COUNT(*)
    FROM sys.columns
    WHERE object_id = OBJECT_ID('dbo.factsales')
      AND name NOT IN ('salesid','datekey','productid','customerid','storeid','promoid',
                       'qty','unitprice','taxrate_pct','net','payment','channel','shipcost','isreturn',
                       'shipweight','discountapplied','returnreason','deliverydays',
                       'grossvalue','discountamount','taxamount')
    UNION ALL

    -- 3. All five core dimension tables have a primary key
    SELECT
        'dimension_keys',
        'all five dimension tables (dimdate, dimproduct, dimcustomer, dimstore, dimpromotion) have a primary key' AS check_description,
        CASE WHEN COUNT(DISTINCT parent_object_id) = 5 THEN 'OK' ELSE 'ISSUE' END,
        COUNT(DISTINCT parent_object_id)
    FROM sys.key_constraints
    WHERE type = 'PK' AND parent_object_id IN (OBJECT_ID('dbo.dimdate'), OBJECT_ID('dbo.dimproduct'),
                                               OBJECT_ID('dbo.dimcustomer'), OBJECT_ID('dbo.dimstore'),
                                               OBJECT_ID('dbo.dimpromotion'))
    UNION ALL

    -- 4. Performance: factsales should have a clustered columnstore index for large volumes
    SELECT
        'performance',
        'factsales has a clustered columnstore index (recommended for large fact tables)' AS check_description,
        CASE WHEN COUNT(*) = 1 THEN 'OK' ELSE 'ISSUE' END,
        COUNT(*)
    FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.factsales') AND type_desc = 'CLUSTERED COLUMNSTORE'
    UNION ALL

    -- 5. Referential integrity: no orphan rows in factsales (all foreign keys valid)
    SELECT
        'referential_integrity',
        'no orphan rows in factsales (all foreign keys have matching dimension records)' AS check_description,
        CASE WHEN orphan_count = 0 THEN 'OK' ELSE 'ISSUE' END,
        orphan_count
    FROM (SELECT COUNT(*) AS orphan_count
          FROM dbo.factsales f
          LEFT JOIN dbo.dimdate d ON f.datekey = d.datekey
          LEFT JOIN dbo.dimproduct p ON f.productid = p.productid
          LEFT JOIN dbo.dimcustomer c ON f.customerid = c.customerid
          LEFT JOIN dbo.dimstore s ON f.storeid = s.storeid
          LEFT JOIN dbo.dimpromotion pr ON f.promoid = pr.promoid
          WHERE d.datekey IS NULL OR p.productid IS NULL OR c.customerid IS NULL
             OR s.storeid IS NULL OR pr.promoid IS NULL) AS orphan_check
)
SELECT check_category, check_description, check_result, details
FROM model_checks
ORDER BY CASE WHEN check_result = 'ISSUE' THEN 0 ELSE 1 END, check_category;
GO

-- =====================================================================
-- Final explanatory comment
-- =====================================================================
PRINT '
================================================================================
MODEL VALIDATION COMPLETED - WHAT THIS SCRIPT DOES AND WHY IT IS USEFUL

This script validates the overall database model structure after loading data
from CSV files generated by Python script v46. It checks for:

1. Star schema integrity: Are all foreign keys from factsales to the five dimensions present?
2. Fact table purity: Does factsales contain only the expected columns (no extra or missing columns)?
3. Dimension keys: Do all five dimension tables have a primary key?
4. Performance: Is there a clustered columnstore index on factsales (critical for fast queries on large data)?
5. Referential integrity: Are there any orphan rows in factsales (rows with foreign keys that point to non‑existent dimension records)?

How it works:
- The script queries system catalog views (sys.foreign_keys, sys.columns, sys.key_constraints, sys.indexes)
  and performs a single SQL query (orphan check) on the data.
- Results are presented as a table with check category, description, result (OK/ISSUE), and details.
- Checks are executed in a single CTE, making it fast and easy to read.

Why it is useful in this project:
- The retailanalytics database is designed as a star schema. This script confirms that the physical
  implementation matches the intended design, which is essential for Power BI reporting.
- Ensuring that factsales has the correct columns prevents unexpected errors when building reports.
- The clustered columnstore index is crucial for query performance on 5 million rows; this check
  guarantees it exists.
- Referential integrity ensures that all sales transactions can be correctly joined to dimensions,
  avoiding missing data in analytics.
- Unlike the data quality script (which checks values), this script validates the structure and
  relationships, complementing the quality checks.

All checks are adapted to the final schema (no dimmanager, no denormalized columns). The script
returns "OK" for each check if the model meets expectations. It is a best practice to run this
after every database load to catch structural issues early.
================================================================================
';
GO