# ============================================================================
# ingest_bronze_layer.py
# ============================================================================
# Author:           DataGen AI & Assistant
# Created:          2026-05-23
# Last modified:    2026-05-25 19:40:00 UTC
# Suggested name:   ingest_bronze_layer.py
# Description:
#   Fabric notebook – Bronze layer ingestion.
#   Reads the six CSV files generated by final_retail_gen.py from the
#   Lakehouse "Files/raw/" folder using explicit schemas for maximum speed.
#   Applies proper Delta overwrite properties and avoids the "Tiny Files"
#   partitioning antipattern on the 10M fact table.
#   Adds audit columns for metadata and lineage tracking.
# ============================================================================

from pyspark.sql import SparkSession
from pyspark.sql.functions import input_file_name, current_timestamp, lit
from pyspark.sql.types import StructType, StructField, IntegerType, StringType, DoubleType, DateType, ShortType, ByteType, LongType
from notebookutils import mssparkutils

# ---------------------------------------------------------------------------
# 1. Initialise Spark session and define schemas
# ---------------------------------------------------------------------------
spark = SparkSession.builder.getOrCreate()

# Explicitly defining schemas to avoid expensive "inferSchema" scans on 10M rows
date_schema = StructType([
    StructField("datekey", IntegerType(), False),
    StructField("fulldate", DateType(), False),
    StructField("year", ShortType(), False),
    StructField("quarternumber", ByteType(), False),
    StructField("quartername", StringType(), False),
    StructField("monthnumber", ByteType(), False),
    StructField("monthname", StringType(), False),
    StructField("weekdaynumber", ByteType(), False),
    StructField("weekdayname", StringType(), False),
    StructField("isweekend", ByteType(), False),
    StructField("yearmonth", StringType(), False),
    StructField("yearmonthnumber", IntegerType(), False),
    StructField("yearquarter", StringType(), False),
    StructField("yearquarternumber", IntegerType(), False),
    StructField("yearweek", StringType(), False),
    StructField("yearweeknumber", IntegerType(), False),
    StructField("isholiday", ByteType(), False)
])

customer_schema = StructType([
    StructField("customerid", IntegerType(), False),
    StructField("fullname", StringType(), False),
    StructField("email", StringType(), False),
    StructField("age", ByteType(), False),
    StructField("gender", StringType(), False),
    StructField("city", StringType(), False),
    StructField("tier", StringType(), False),
    StructField("points", IntegerType(), False),
    StructField("isactive", ByteType(), False),
    StructField("lang", StringType(), False),
    StructField("totalspend", DoubleType(), False),
    StructField("regdate", DateType(), False),
    StructField("annualincome", DoubleType(), False),
    StructField("incomebracket", StringType(), False),
    StructField("education", StringType(), False),
    StructField("maritalstatus", StringType(), False),
    StructField("childrencount", ByteType(), False),
    StructField("loyaltysegment", StringType(), False),
    StructField("satisfactionscore", DoubleType(), False),
    StructField("dayssincelastpurchase", IntegerType(), False),
    StructField("hassubscription", ByteType(), False),
    StructField("preferredcontact", StringType(), False),
    StructField("spendmultiplier", DoubleType(), False)
])

product_schema = StructType([
    StructField("productid", IntegerType(), False),
    StructField("name", StringType(), False),
    StructField("category", StringType(), False),
    StructField("brand", StringType(), False),
    StructField("unitcost", DoubleType(), False),
    StructField("unitprice", DoubleType(), False),
    StructField("margin_pct", DoubleType(), False),
    StructField("weight", DoubleType(), False),
    StructField("color", StringType(), False),
    StructField("material", StringType(), False),
    StructField("supplierid", IntegerType(), False),
    StructField("isactive", ByteType(), False),
    StructField("minstock", IntegerType(), False),
    StructField("tax_rate", DoubleType(), False),
    StructField("haswarranty", ByteType(), False),
    StructField("ecofriendly", ByteType(), False),
    StructField("seasonalityfactor", DoubleType(), False),
    StructField("warrantymonths", ByteType(), False),
    StructField("ecoscore", IntegerType(), False),
    StructField("releaseyear", ShortType(), False),
    StructField("skucount", IntegerType(), False),
    StructField("isdiscontinued", ByteType(), False),
    StructField("productrating", DoubleType(), False),
    StructField("stockstatus", StringType(), False)
])

store_schema = StructType([
    StructField("storeid", IntegerType(), False),
    StructField("storename", StringType(), False),
    StructField("city", StringType(), False),
    StructField("type", StringType(), False),
    StructField("staff", ShortType(), False),
    StructField("sizem2", IntegerType(), False),
    StructField("hascafe", ByteType(), False),
    StructField("openingyear", ShortType(), False),
    StructField("region", StringType(), False),
    StructField("renovationyear", ShortType(), False),
    StructField("parkingspots", ShortType(), False),
    StructField("storerating", DoubleType(), False),
    StructField("hasdeliveryservice", ByteType(), False),
    StructField("floornumber", ByteType(), False),
    StructField("distancetocitycenterkm", DoubleType(), False),
    StructField("annualrentcost", DoubleType(), False),
    StructField("storesizemultiplier", DoubleType(), False)
])

promotion_schema = StructType([
    StructField("promoid", IntegerType(), False),
    StructField("promoname", StringType(), False),
    StructField("discount_pct", DoubleType(), False),
    StructField("discount_fixed", DoubleType(), False),
    StructField("type", StringType(), False),
    StructField("isactive", ByteType(), False),
    StructField("minspend", IntegerType(), False),
    StructField("channel", StringType(), False),
    StructField("budget", DoubleType(), False),
    StructField("startdate", DateType(), False),
    StructField("enddate", DateType(), False),
    StructField("targetaudience", StringType(), False),
    StructField("maxdiscountcap", DoubleType(), False),
    StructField("isstackable", ByteType(), False),
    StructField("redemption_rate", DoubleType(), False),
    StructField("coderequired", ByteType(), False),
    StructField("promoupliftfactor", DoubleType(), False)
])

sales_schema = StructType([
    StructField("salesid", LongType(), False),
    StructField("datekey", IntegerType(), False),
    StructField("productid", IntegerType(), False),
    StructField("customerid", IntegerType(), False),
    StructField("storeid", IntegerType(), False),
    StructField("promoid", IntegerType(), False),
    StructField("qty", IntegerType(), False),
    StructField("unitprice", DoubleType(), False),
    StructField("tax_rate", DoubleType(), False),
    StructField("net", DoubleType(), False),
    StructField("payment", StringType(), False),
    StructField("channel", StringType(), False),
    StructField("grossvalue", DoubleType(), False),
    StructField("discountamount", DoubleType(), False),
    StructField("taxamount", DoubleType(), False),
    StructField("shipcost", DoubleType(), False),
    StructField("isreturn", ByteType(), False),
    StructField("shipweight", DoubleType(), False),
    StructField("discountapplied", ByteType(), False),
    StructField("returnreason", StringType(), False),
    StructField("deliverydays", ByteType(), False),
    StructField("hour", ByteType(), False)
])

# Medallion schemas configuration
bronze_schema = "`01_bronze_db`"
silver_schema = "`02_silver_db`"
gold_schema   = "`03_gold_db`"

spark.sql(f"CREATE DATABASE IF NOT EXISTS {bronze_schema}")
spark.sql(f"CREATE DATABASE IF NOT EXISTS {silver_schema}")
spark.sql(f"CREATE DATABASE IF NOT EXISTS {gold_schema}")

# ---------------------------------------------------------------------------
# 2. Define mapping between CSV file paths, target tables, and schemas
#    All CSV files are expected to reside in the Lakehouse "Files/raw/" folder.
# ---------------------------------------------------------------------------
csv_mapping = [
    ("raw/dim_date.csv",       "bronze_dimdate",      date_schema),
    ("raw/dim_customer.csv",   "bronze_dimcustomer",  customer_schema),
    ("raw/dim_product.csv",    "bronze_dimproduct",   product_schema),
    ("raw/dim_store.csv",      "bronze_dimstore",     store_schema),
    ("raw/dim_promotion.csv",  "bronze_dimpromotion", promotion_schema),
    ("raw/fact_sales.csv",     "bronze_factsales",    sales_schema),
]

# ---------------------------------------------------------------------------
# 3. Ingestion Loop
# ---------------------------------------------------------------------------
for csv_path, table_name, schema in csv_mapping:
    full_path = f"Files/{csv_path}"

    # Skip missing files gracefully
    if not mssparkutils.fs.exists(full_path):
        print(f"WARNING: File not found – {full_path}")
        continue

    print(f"Ingesting {csv_path} with explicit schema definition...")

    # Read CSV using the pre-defined strict schema (rapid ingestion)
    df = spark.read \
              .option("header", "true") \
              .schema(schema) \
              .csv(full_path)

    # Add audit columns for end-to-end data lineage
    df = df.withColumn("_source_file",   input_file_name())   \
           .withColumn("_ingestion_ts",  current_timestamp())  \
           .withColumn("_file_name",     lit(csv_path))

    # Optimizing partitioning for the 10M rows fact table
    # Avoids creating 1200+ micro-partitions (the "Tiny Files" antipattern)
    # Coalescing into 4 larger partitions (~100MB each) is optimal for Delta reads
    if "fact" in table_name:
        df = df.repartition(4)

    # Overwrite the Delta table atomically (idempotent and safe)
    # Uses option("overwriteSchema", "true") to update catalog without dropping
    df.write \
      .format("delta") \
      .mode("overwrite") \
      .option("overwriteSchema", "true") \
      .saveAsTable(f"{bronze_schema}.{table_name}")

    row_count = df.count()
    print(f"✓ Loaded {row_count:,} rows into {bronze_schema}.{table_name}\n")

print("Bronze layer ingestion completed successfully.")
# ============================================================================
# End of ingest_bronze_layer.py
# ============================================================================