# ============================================================================
# ingest_bronze_layer.py
# ============================================================================
# Author:           DataGen AI
# Created:           2026-05-23
# Last modified:     2026-05-24 03:00:00 UTC
# Suggested name:    ingest_bronze_layer.py
# Description:
#   Fabric notebook – Bronze layer ingestion.
#   Reads the six CSV files generated by final_retail_gen.py from the
#   Lakehouse "Files/raw/" folder, adds audit columns (source file name,
#   ingestion timestamp, original file path), and writes them as Delta
#   tables into the 01_bronze_db schema.
#   Existing bronze tables are dropped first to ensure a clean start.
#   The large fact table is repartitioned by datekey (or a fixed number
#   of partitions) for better write parallelism.
#
# Execution order (medallion architecture):
#   1. ingest_bronze_layer.py   ← this notebook
#   2. transform_silver_layer.py
#   3. create_gold_views.py
#   4. optimize_delta_tables.py
# ============================================================================

from pyspark.sql import SparkSession
from pyspark.sql.functions import input_file_name, current_timestamp, lit
from notebookutils import mssparkutils

# ---------------------------------------------------------------------------
# 1. Initialise Spark session and create databases if they do not exist
# ---------------------------------------------------------------------------
spark = SparkSession.builder.getOrCreate()

bronze_schema = "`01_bronze_db`"
silver_schema = "`02_silver_db`"
gold_schema   = "`03_gold_db`"

spark.sql(f"CREATE DATABASE IF NOT EXISTS {bronze_schema}")
spark.sql(f"CREATE DATABASE IF NOT EXISTS {silver_schema}")
spark.sql(f"CREATE DATABASE IF NOT EXISTS {gold_schema}")

# ---------------------------------------------------------------------------
# 2. Clean start – drop all existing bronze tables
#    This guarantees that the ingestion is idempotent and always loads
#    the latest CSV files.
# ---------------------------------------------------------------------------
existing_tables = spark.sql(f"SHOW TABLES IN {bronze_schema}").collect()
for row in existing_tables:
    spark.sql(f"DROP TABLE IF EXISTS {bronze_schema}.{row.tableName}")
    print(f"Dropped {bronze_schema}.{row.tableName}")

# ---------------------------------------------------------------------------
# 3. Define mapping between CSV file paths and target Delta table names
#    All CSV files are expected to reside in the Lakehouse "Files/raw/" folder.
# ---------------------------------------------------------------------------
csv_mapping = [
    ("raw/dim_date.csv",       "bronze_dimdate"),
    ("raw/dim_customer.csv",   "bronze_dimcustomer"),
    ("raw/dim_product.csv",    "bronze_dimproduct"),
    ("raw/dim_store.csv",      "bronze_dimstore"),
    ("raw/dim_promotion.csv",  "bronze_dimpromotion"),
    ("raw/fact_sales.csv",     "bronze_factsales"),
]

# ---------------------------------------------------------------------------
# 4. Loop through each CSV file, load it into a DataFrame, add audit
#    columns, optimise partitioning, and write as a Delta table.
# ---------------------------------------------------------------------------
for csv_path, table_name in csv_mapping:
    full_path = f"Files/{csv_path}"

    # Skip missing files gracefully
    if not mssparkutils.fs.exists(full_path):
        print(f"WARNING: File not found – {full_path}")
        continue

    # Read CSV with header and automatic schema inference
    df = spark.read \
              .option("header", "true") \
              .option("inferSchema", "true") \
              .csv(full_path)

    # Add audit columns for data lineage tracking
    df = df.withColumn("_source_file",   input_file_name())   \
           .withColumn("_ingestion_ts",  current_timestamp())  \
           .withColumn("_file_name",     lit(csv_path))

    # Repartition the large fact table for better write parallelism
    # If the datekey column exists (which it does), partition by it;
    # otherwise fall back to a fixed 20 partitions.
    if "fact" in table_name:
        if "datekey" in df.columns:
            df = df.repartition("datekey")
        else:
            df = df.repartition(20)

    # Overwrite the Delta table (idempotent – safe for re‑runs)
    df.write \
      .format("delta") \
      .mode("overwrite") \
      .saveAsTable(f"{bronze_schema}.{table_name}")

    row_count = df.count()
    print(f"Loaded {row_count:,} rows into {bronze_schema}.{table_name}")

print("Bronze layer ingestion completed successfully.")
# ============================================================================
# End of ingest_bronze_layer.py
# ============================================================================